# Generated by Django 3.2.25 on 2024-10-11 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Centr', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuAbout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=70, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
            ],
        ),
    ]
