# Generated by Django 3.2.25 on 2024-10-11 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Centr', '0005_auto_20241011_2341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuabout',
            name='type',
            field=models.CharField(choices=[('OsS', 'Основные сведенения'), ('Dok', 'Документы'), ('Obr', 'Образование'), ('POU', 'Платные образовательные услуги'), ('RPN', 'Руководство. Педагогический (научно-педагогический) состав')], default='OsS', max_length=5, verbose_name='Тип'),
        ),
    ]
