# Generated by Django 3.2.25 on 2024-10-20 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Centr', '0011_teacher_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menutrainingcent',
            name='price',
        ),
    ]
