# Generated by Django 3.2.25 on 2024-11-04 07:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Centr', '0014_more_detailed'),
    ]

    operations = [
        migrations.AddField(
            model_name='menutrainingcent',
            name='program',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='program', to='Centr.more_detailed'),
        ),
    ]
