# Generated by Django 3.2.25 on 2024-11-04 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Centr', '0016_remove_menutrainingcent_program'),
    ]

    operations = [
        migrations.AddField(
            model_name='more_detailed',
            name='kurs',
            field=models.CharField(default=1, max_length=70, verbose_name='Указать название курса пример Педагогика или менеджмент'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='more_detailed',
            name='type',
            field=models.CharField(choices=[('PPD', 'Переподготовка'), ('DPD', 'Доподготовка')], default='PPD', max_length=3, verbose_name='Тип'),
        ),
    ]
