# Generated by Django 3.2.25 on 2024-11-04 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Centr', '0017_auto_20241104_1735'),
    ]

    operations = [
        migrations.AlterField(
            model_name='more_detailed',
            name='kurs',
            field=models.CharField(blank=True, max_length=70, verbose_name='Указать название курса пример Педагогика или менеджмент'),
        ),
    ]
