# Generated by Django 3.2.25 on 2024-10-12 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Centr', '0009_teacher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuabout',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Название'),
        ),
    ]
