# Generated by Django 3.2.25 on 2024-10-12 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Centr', '0010_alter_menuabout_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images', verbose_name='Изображение'),
        ),
    ]
