# Generated by Django 3.2.25 on 2024-10-20 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Centr', '0012_remove_menutrainingcent_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='menutrainingcent',
            name='value_programs',
            field=models.IntegerField(default=1, verbose_name='количество программ обучения'),
        ),
    ]
