# Generated by Django 3.2.25 on 2024-11-09 14:59

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Centr', '0019_card_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='card_info',
            name='learning_plan',
            field=models.FileField(blank=True, storage=django.core.files.storage.FileSystemStorage(location='media/'), upload_to='learning_plans/', verbose_name='Учебный план (PDF)'),
        ),
    ]
